version: '3.8'

services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - poc-db-data:/var/lib/postgresql/data
    container_name: db

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    # volumes:
    #   - ./apps/api/src:/app/src
    command: npm run dev
    ports:
      - '3000:3000'
    depends_on:
      - db
    container_name: api

  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    # volumes:
    #   - ./apps/client/src:/app/src
    command: npm run dev
    ports:
      - '5173:5173'
    depends_on:
      - api
    container_name: client

volumes:
  poc-db-data: