version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    volumes:
      - ./src:/app/src
    command: npm run start:dev
    ports:
      - '4000:3000'
    depends_on:
      - db
    container_name: backend
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - poc-db-data:/var/lib/postgresql/data
    container_name: db

volumes:
  poc-db-data: