name: Deploy client to Netlify

on:
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "deploy-group"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Test code
        run: npm run test:client
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: "Create env file"
        run: |
          touch .env
          echo VITE_API_BASE_ENDPOINT=${{ secrets.API_BASE_ENDPOINT }} >> .env
          cat .env
      - name: Build project
        run: npm run build:client
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: apps/client/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: apps/client/dist
      - name: Deploy to Netlify
        id: deploy-step
        uses: nwtgck/actions-netlify@v2.1.0
        with:
          publish-dir: "./apps/client/dist"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Testing workflow (2)"
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Display output
        run: echo "Deployed on ${{ steps.deploy-step.outputs.deploy-url }}"
